### ISSUE TITLE
Modify Code Styling

### ISSUE THREAD

**Issue by khalidabuhakmeh** [ritterim/ritterim.github.io#21]
I'd like to change the code styling to this.

``` css
.post-content p code, .post-content li code {
    padding: 3px 6px;
    color: #3085f4;
    background-color: #eee;
    border-radius: 4px;
}
```

![copying_app_settings_and_connection_strings_between_azure_web_apps](https://cloud.githubusercontent.com/assets/228256/12276383/73d677c8-b943-11e5-9389-53bf681d3b5d.png)
